# config/packages/security.yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            # Ajout de la configuration form_login
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                username_parameter: email
                password_parameter: _password
                default_target_path: app_dashboard  # Route après connexion réussie
            logout:
                path: app_logout
                target: app_auth

    access_control:
        - { path: ^/register/step1, roles: PUBLIC_ACCESS }
        - { path: ^/register/step2, roles: PUBLIC_ACCESS }
        - { path: ^/home, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
